meta_name: "MauRide"
meta_title: "MauRide - Carpooling lovers"
meta_description: "Carpooling in Mauritius, find a ride or a carpooler !"
# meta_image: "cover.png" # should exist in `app/assets/images/`
